FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./

#  Clean install dependencies
RUN npm ci --include=dev

# Copy rest of the project
COPY . .

# Expose port Vite dev server uses
EXPOSE 5173

# Run Vite development server
CMD ["npm", "run", "dev"]
