FROM ollama/ollama:latest

# Preload your model (e.g., deepseek-r1:1.5b)
# RUN ollama pull deepseek-r1:7b

# Expose default Ollama port
EXPOSE 11434

# Start Ollama server when container runs
CMD ["serve"]
