services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    container_name: qualai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant
      - ollama
    environment:
      # Hugging Face / Transformers
      HF_HOME: /tmp/huggingface
      TRANSFORMERS_CACHE: /tmp/huggingface
      TORCH_HOME: /tmp/torch

      # Matplotlib
      MPLCONFIGDIR: /tmp/matplotlib

      # NeMo + Lhotse
      NEMO_HOME: /tmp/nemo
      LHOTSE_CACHE_DIR: /tmp/lhotse
      LHOTSE_TOOLS_CACHE: /tmp/lhotse/tools 
    volumes:
      - ./server:/app # Optional: dev hot reload
      - ./server/cache:/home/app
      - ./papers:/papers
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: qualai-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true # important for file watching inside Docker
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/entrypoint.py:/entrypoint.py # Mount the new Python script
      - ollama_setup:/setup # This volume remains the same
    entrypoint: ["python3", "/entrypoint.py"] # Set the entrypoint to our script

volumes:
  qdrant_data:
  ollama_data:
  ollama_setup: # Add the new volume for the setup marke
