# Use slim Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libsqlite3-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI application code
COPY ./app ./app
COPY ./data ./data
COPY ./scripts ./scripts


# Expose FastAPI port
EXPOSE 8000

# Setup an app user so the container doesn't run as the root user
RUN useradd -m app
ENV HF_HOME=/home/app/.cache/huggingface
RUN chown -R app:app /home/app
USER app

# Run FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
