# --- Development Backend Dockerfile ---
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies once
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libsqlite3-dev \
    libasound2 \
    ffmpeg \
    curl \
    git \
    wget \
    ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

RUN mkdir -p "/app/Interview Uploads" && chmod 777 "/app/Interview Uploads"

RUN pip install --no-cache-dir python-dotenv
RUN pip install --no-cache-dir cython
# Install pip + requirements
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
    
COPY app/whisper-diarization/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt



RUN useradd app && chown -R app:app /app
USER app
# Default: mount code with volumes (no COPY here!)
EXPOSE 8000

CMD ["python", "start.py"]
